In [35]:
!pip install pandas numpy matplotlib seaborn scikit-learn

Requirement already satisfied: pandas in c:\users\sayye\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: numpy in c:\users\sayye\anaconda3\lib\site-packages (2.3.5)
Requirement already satisfied: matplotlib in c:\users\sayye\anaconda3\lib\site-packages (3.10.6)
Requirement already satisfied: seaborn in c:\users\sayye\anaconda3\lib\site-packages (0.13.2)
Requirement already satisfied: scikit-learn in c:\users\sayye\anaconda3\lib\site-packages (1.7.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\sayye\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\sayye\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\sayye\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\sayye\anaconda3\lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\sayye\anaconda3\lib\site-packages (from matplotlib) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\sayye\anaconda3\lib\site-packages (from matplotlib) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\sayye\anaconda3\lib\site-packages (from matplotlib) (1.4.9)
Requirement already satisfied: packaging>=20.0 in c:\users\sayye\anaconda3\lib\site-packages (from matplotlib) (25.0)
Requirement already satisfied: pillow>=8 in c:\users\sayye\anaconda3\lib\site-packages (from matplotlib) (12.0.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\sayye\anaconda3\lib\site-packages (from matplotlib) (3.2.5)
Requirement already satisfied: scipy>=1.8.0 in c:\users\sayye\anaconda3\lib\site-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in c:\users\sayye\anaconda3\lib\site-packages (from scikit-learn) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\sayye\anaconda3\lib\site-packages (from scikit-learn) (3.5.0)
Requirement already satisfied: six>=1.5 in c:\users\sayye\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [36]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split, cross_val_score, StratifiedKFold
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, roc_auc_score, confusion_matrix, classification_report, roc_curve

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC

import warnings
warnings.filterwarnings('ignore')

In [37]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

!pip install openpyxl

In [38]:
import pandas as pd

train_df = pd.read_csv("train.csv")
test_df = pd.read_csv("test.csv")

train_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [39]:
import os
os.listdir()

['.anaconda',
 '.conda',
 '.continuum',
 '.idlerc',
 '.ipynb_checkpoints',
 '.ipython',
 '.jupyter',
 '.matplotlib',
 '.ms-ad',
 '.vscode',
 'aiman zaidi.py',
 'Aiman.py',
 'anaconda3',
 'AppData',
 'Application Data',
 'Contacts',
 'Cookies',
 'Documents',
 'Downloads',
 'Favorites',
 'Helloworld.c',
 'Links',
 'Local Settings',
 'Music',
 'My Documents',
 'NetHood',
 'NTUSER.DAT',
 'ntuser.dat.LOG1',
 'ntuser.dat.LOG2',
 'NTUSER.DAT{16e5eb6f-ea24-11ef-8d67-f95e5fda516e}.TM.blf',
 'NTUSER.DAT{16e5eb6f-ea24-11ef-8d67-f95e5fda516e}.TMContainer00000000000000000001.regtrans-ms',
 'NTUSER.DAT{16e5eb6f-ea24-11ef-8d67-f95e5fda516e}.TMContainer00000000000000000002.regtrans-ms',
 'ntuser.ini',
 'OneDrive',
 'prac 17.png',
 'prac 19.png',
 'prac 2.png',
 'prac 4.png',
 'prac 5.png',
 'PrintHood',
 'program.py',
 'Recent',
 'Saved Games',
 'Searches',
 'SendTo',
 'Start Menu',
 'submission.csv',
 'Templates',
 'test.csv',
 'Titanic.ipynb',
 'train.csv',
 'Untitled.ipynb',
 'Untitled1.ipynb',
 'Videos',
 'WPS Cloud Files',
 'WPSDrive']

In [40]:
train_df.info()
train_df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [41]:
train_df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [42]:
train_df['Age'].fillna(train_df['Age'].mean(), inplace=True)

In [43]:
train_df.drop('Cabin', axis=1, inplace=True)

In [44]:
train_df['Embarked'].fillna(train_df['Embarked'].mode()[0], inplace=True)

In [45]:
train_df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

In [46]:
train_df['Sex'] = train_df['Sex'].map({'male':0,'female':1})
train_df['Embarked'] = train_df['Embarked'].map({'S':0,'C':1,'Q':2})

In [47]:
X = train_df[['Pclass','Sex','Age','SibSp','Parch','Fare','Embarked']]
y = train_df['Survived']

In [48]:
from sklearn.model_selection import train_test_split

X_train,X_val,y_train,y_val = train_test_split(
    X,y,test_size=0.2,random_state=42
)

In [49]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

model = RandomForestClassifier()
model.fit(X_train,y_train)

preds = model.predict(X_val)

accuracy_score(y_val,preds)

0.7988826815642458

In [50]:
test_df['Age'].fillna(test_df['Age'].mean(), inplace=True)
test_df['Fare'].fillna(test_df['Fare'].mean(), inplace=True)

test_df.drop('Cabin', axis=1, inplace=True)

test_df['Embarked'].fillna(test_df['Embarked'].mode()[0], inplace=True)

test_df['Sex'] = test_df['Sex'].map({'male':0,'female':1})
test_df['Embarked'] = test_df['Embarked'].map({'S':0,'C':1,'Q':2})

In [51]:
X_test = test_df[['Pclass','Sex','Age','SibSp','Parch','Fare','Embarked']]

In [52]:
test_preds = model.predict(X_test)

In [55]:
submission = pd.DataFrame({
    'PassengerId': test_df['PassengerId'],
    'Survived': test_preds})

submission.to_csv("submission.csv", index=False)